POST http://localhost:3001/api/persons/new
Content-Type: application/json

{
    "name": "test4",
    "number": "132-956874"
}

###
GET https://phone-book-hg3w.onrender.com/api/persons

###
DELETE http://localhost:3001/api/persons/64c8d06eeb1ee0fb4ca73490

###
PUT http://localhost:3001/api/persons/64c8e38111c3f926d6949426
Content-Type: application/json

{
    "name": "jade tam",
    "number": "456-789123"
}