POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "te",
    "number": "1-956874"
}

###
GET https://phone-book-hg3w.onrender.com/api/persons

###
DELETE http://localhost:3001/api/persons/64c9044c968b24be1839deaf

###
PUT http://localhost:3001/api/persons/64c9044c968b24be1839deaf
Content-Type: application/json

{
    "name": "jade tam",
    "number": "456-789123"
}